import { StyleSheet } from 'react-native';

export const fonts = StyleSheet.create({
  header1: {
    fontFamily: 'System',
    fontWeight: 'bold',
    fontSize: 36,
    lineHeight: 40,
    letterSpacing: -0.24,
    color: '#283244',
  },
  header2: {
    fontFamily: 'System',
    fontWeight: 'bold',
    fontSize: 19,
    lineHeight: 25,
    letterSpacing: -0.24,
    color: '#283244',
  },
  body1: {
    fontFamily: 'System',
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 25,
    letterSpacing: -0.24,
    color: '#283244',
  },
  body1Regular: {
    fontFamily: 'System',
    fontSize: 14,
    lineHeight: 25,
    letterSpacing: -0.24,
    color: '#283244',
  },
  body1Light: {
    fontFamily: 'System',
    fontSize: 14,
    lineHeight: 25,
    letterSpacing: -0.24,
    color: '#283244B2',
  },
  body1Black: {
    fontFamily: 'System',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: -0.24,
    color: '#000000',
  },
  body2: {
    fontFamily: 'System',
    fontSize: 10,
    lineHeight: 20,
    letterSpacing: -0.24,
    color: '#283244B2',
  },
  fButton: {
    fontFamily: 'System',
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: -0.24,
    textAlign: 'center',
    color: '#FFFFFF',
  },
  fBack: {
    fontFamily: 'System',
    fontSize: 18,
    textAlign: 'left',
    color: '#283244',
    marginStart: 2,
  },
});
